from Business import Business

businesses = {
    0: Business(
        name="City Bakery",
        owner_name="Alice Smith",
        description="Freshly baked bread and pastries.",
        category="Food",
        address="123 Main St, Downtown, Orange County",
        latitude=33.787914,
        longitude=-117.853104,
        phone="123-456-7890",
        website="http://citybakery.com",
        social_media_links=["https://instagram.com/citybakery"],
        opening_hours="Mon-Fri: 7 AM - 6 PM"
    ),
    1: Business(
        name="Tattoo Art",
        owner_name="John Doe",
        description="Custom tattoo designs and body art.",
        category="Tattoos",
        address="456 Oak Ave, Uptown, Orange County",
        latitude=33.787914,
        longitude=-117.893227,
        phone="987-654-3210",
        social_media_links=["https://facebook.com/tattooart"],
        opening_hours="Tue-Sat: 10 AM - 8 PM"
    ),
    2: Business(
        name="Quick Fix Haircuts",
        owner_name="Mary Lee",
        description="Affordable and stylish haircuts for men and women.",
        category="Haircuts",
        address="789 Birch Rd, Westside, Orange County",
        latitude=33.787914,
        longitude=-117.867833,
        phone="555-123-4567",
        opening_hours="Mon-Fri: 9 AM - 7 PM, Sat: 9 AM - 5 PM"
    ),
    3: Business(
        name="The Art Corner",
        owner_name="James Brown",
        description="Handmade crafts and original artworks.",
        category="Handmade Crafts",
        address="321 Elm St, Southside, Orange County",
        latitude=33.787914,
        longitude=-117.865589,
        phone="555-987-6543",
        website="http://theartcorner.com",
        social_media_links=["https://instagram.com/theartcorner"],
        opening_hours="Wed-Sun: 11 AM - 6 PM"
    ),
    4: Business(
        name="Paws & Claws Pet Grooming",
        owner_name="Samantha Green",
        description="Pet grooming and spa services for dogs and cats.",
        category="Other",
        address="102 Pine Dr, Eastside, Orange County",
        latitude=33.787914,
        longitude=-117.853111,
        phone="555-555-5555",
        opening_hours="Mon-Fri: 8 AM - 6 PM"
    ),
    5: Business(
        name="The Coffee House",
        owner_name="Robert White",
        description="Specialty coffees and baked goods.",
        category="Beverages",
        address="654 Maple St, Downtown, Orange County",
        latitude=33.787914,
        longitude=-117.853104,
        phone="555-123-6789",
        social_media_links=["https://facebook.com/thecoffeehouse"],
        opening_hours="Mon-Sun: 6 AM - 9 PM"
    ),
    6: Business(
        name="Delicious Diner",
        owner_name="Olivia Blue",
        description="Comfort food, burgers, and fries.",
        category="Food",
        address="987 Pine St, Uptown, Orange County",
        latitude=33.787914,
        longitude=-117.893227,
        phone="555-234-9876",
        opening_hours="Mon-Sun: 8 AM - 10 PM"
    ),
    7: Business(
        name="Shine Beauty",
        owner_name="Ella Adams",
        description="Beauty treatments and skincare services.",
        category="Other",
        address="135 Oak Blvd, Northside, Orange County",
        latitude=33.787914,
        longitude=-117.867833,
        phone="555-345-1234",
        website="http://shinebeauty.com",
        social_media_links=["https://instagram.com/shinebeauty"],
        opening_hours="Tue-Sat: 10 AM - 6 PM"
    ),
    8: Business(
        name="Tech World",
        owner_name="George Clark",
        description="Electronics and tech gadgets store.",
        category="Other",
        address="234 Cedar St, Westside, Orange County",
        latitude=33.787914,
        longitude=-117.865589,
        phone="555-456-7890",
        opening_hours="Mon-Sun: 10 AM - 8 PM"
    ),
    9: Business(
        name="Sushi Time",
        owner_name="Chloe King",
        description="Fresh sushi and Japanese cuisine.",
        category="Food",
        address="876 Cherry Ave, Eastside, Orange County",
        latitude=33.787914,
        longitude=-117.853104,
        phone="555-567-8901",
        social_media_links=["https://instagram.com/sushitime"],
        opening_hours="Mon-Sun: 11 AM - 10 PM"
    ),
    10: Business(
        name="Fit & Strong Gym",
        owner_name="Liam Harris",
        description="Gym for strength training and fitness.",
        category="Other",
        address="543 Birch Rd, Southside, Orange County",
        latitude=33.787914,
        longitude=-117.853104,
        phone="555-678-9012",
        opening_hours="Mon-Sun: 6 AM - 9 PM"
    ),
    11: Business(
        name="Craft Beer Brewery",
        owner_name="Sophia Miller",
        description="Craft beer and local brews.",
        category="Beverages",
        address="111 Maple Blvd, Downtown, Orange County",
        latitude=33.787914,
        longitude=-117.853104,
        phone="555-789-0123",
        opening_hours="Mon-Sun: 12 PM - 8 PM"
    ),
    12: Business(
        name="Spicy Tacos",
        owner_name="Benjamin Scott",
        description="Authentic Mexican street tacos.",
        category="Food",
        address="456 Cedar St, Uptown, Orange County",
        latitude=33.787914,
        longitude=-117.853104,
        phone="555-890-1234",
        opening_hours="Mon-Sun: 10 AM - 9 PM"
    ),
    13: Business(
        name="The Vintage Shop",
        owner_name="Charlotte Moore",
        description="Vintage clothing and accessories.",
        category="Handmade Crafts",
        address="765 Oak Blvd, Westside, Orange County",
        latitude=33.787914,
        longitude=-117.853104,
        phone="555-901-2345",
        opening_hours="Tue-Sun: 11 AM - 6 PM"
    ),
    14: Business(
        name="Yoga & Wellness",
        owner_name="Amelia Turner",
        description="Yoga classes and wellness therapies.",
        category="Other",
        address="321 Maple Rd, Eastside, Orange County",
        latitude=33.787914,
        longitude=-117.853104,
        phone="555-012-3456",
        website="http://yogaandwellness.com",
        social_media_links=["https://instagram.com/yogaandwellness"],
        opening_hours="Mon-Sun: 8 AM - 8 PM"
    )
}
